// lib/providers/tracking_provider.dart

import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

enum TrackingStatus {
  delivered,
  inTransit,
  outForDelivery,
  processing,
  exception,
}

class TrackingEvent {
  final String title, location, timestamp;
  const TrackingEvent({
    required this.title,
    required this.location,
    required this.timestamp,
  });
}

class TrackingResult {
  final String trackingNumber, courier, service,
      origin, destination, estimatedDelivery;
  final Color courierColor;
  final TrackingStatus status;
  final List<TrackingEvent> events;
  final bool isMock; // true for test mode tracking numbers

  const TrackingResult({
    required this.trackingNumber, required this.courier,
    required this.courierColor,  required this.service,
    required this.origin,        required this.destination,
    required this.estimatedDelivery,
    required this.status,        required this.events,
    this.isMock = false,
  });
}

class TrackingProvider extends ChangeNotifier {

  // ── ShipEngine via Supabase Edge Function ─────────────────────
  static const _url =
      'https://tjrjeemaacumepimjltg.supabase.co/functions/v1/shipengine-courier';
  static const _anonKey =
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqcmplZW1hYWN1bWVwaW1qbHRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxMjE2NjAsImV4cCI6MjA4OTY5NzY2MH0.gtBcFu-J48mPDk_S9ukfVdW-7gUmabGatmJ1g1_5zzo';

  // ShipEngine carrier IDs for tracking lookups
  static const _carrierIds = {
    'evri':        'se-376463',
    'dpd':         'se-376464',
    'globalpost':  'se-376465',
    'yodel':       'se-376466',
    'fedex':       'se-376467',
    'royal_mail':  'se-376468',
    'parcelforce': 'se-376469',
  };

  bool isLoading = false;
  bool hasError  = false;
  String errorMessage = '';
  TrackingResult? result;

  Future<void> trackParcel(String trackingNumber) async {
    isLoading    = true;
    hasError     = false;
    errorMessage = '';
    result       = null;
    notifyListeners();

    final tn = trackingNumber.trim().toUpperCase();

    // ── Detect mock/test tracking numbers on Flutter side too ──
    // These start with SWIFT or end with TEST — generated by our test mode
    final isMockNumber = tn.startsWith('SWIFT') || tn.endsWith('TEST')
        || tn.contains('MOCK');

    try {
      final carrierKey = isMockNumber ? 'royal_mail' : _detectCarrierKey(tn);
      final carrierId  = _carrierIds[carrierKey];

      debugPrint('[TrackingProvider] tracking=$trackingNumber '
          'carrier=$carrierKey carrierId=$carrierId');

      final res = await http.post(
        Uri.parse(_url),
        headers: {
          'Content-Type':  'application/json',
          'Authorization': 'Bearer $_anonKey',
        },
        body: jsonEncode({
          'action':         'track',
          'trackingNumber': trackingNumber.trim().toUpperCase(),
          'carrier':        carrierKey,
          'carrierId':      carrierId,
        }),
      ).timeout(const Duration(seconds: 20));

      debugPrint('[TrackingProvider] HTTP ${res.statusCode}: ${res.body}');

      final data = jsonDecode(res.body) as Map<String, dynamic>;

      if (res.statusCode == 200 && _isSuccess(data)) {
        final statusRaw    = _str(data, ['status', 'trackingStatus', 'status_code']);
        final etaRaw       = _str(data, ['eta', 'estimatedDelivery', 'estimated_delivery_at']);
        final eventsRaw    = data['events'] ?? data['tracking_history'] ?? [];
        final isMock       = data['isMock'] == true;

        result = TrackingResult(
          trackingNumber:   _str(data, ['trackingNumber', 'tracking_number']) ?? trackingNumber,
          courier:          _friendlyCarrier(carrierKey),
          courierColor:     _courierColor(carrierKey),
          service:          _str(data, ['servicelevel', 'service', 'service_type']) ?? 'Standard',
          origin:           _str(data, ['originLocation', 'origin']) ?? 'United Kingdom',
          destination:      _str(data, ['destLocation', 'destination']) ?? 'Unknown',
          estimatedDelivery: etaRaw != null ? _formatDate(etaRaw) : 'See carrier website',
          status:           _parseStatus(statusRaw),
          events:           _parseEvents(eventsRaw),
          isMock:           isMock,
        );

        debugPrint('[TrackingProvider] ✓ status=${result!.status} '
            'events=${result!.events.length}');
      } else {
        hasError     = true;
        errorMessage = _str(data, ['error', 'message', 'detail']) ??
            'Tracking number not found. (HTTP ${res.statusCode})';
        debugPrint('[TrackingProvider] ✗ $errorMessage');
      }
    } catch (e, st) {
      hasError     = true;
      errorMessage = 'Network error — please check your connection.';
      debugPrint('[TrackingProvider] Exception: $e\n$st');
    }

    isLoading = false;
    notifyListeners();
  }

  // ── Helpers ───────────────────────────────────────────────────

  String? _str(Map<String, dynamic> map, List<String> keys) {
    for (final k in keys) {
      final v = map[k];
      if (v != null && v.toString().isNotEmpty) return v.toString();
    }
    return null;
  }

  bool _isSuccess(Map<String, dynamic> data) =>
      data['success'] == true ||
          data['status'] != null ||
          data['trackingNumber'] != null ||
          data['tracking_number'] != null;

  List<TrackingEvent> _parseEvents(dynamic raw) {
    if (raw == null || raw is! List) return [];
    return raw.map((e) {
      if (e is! Map) return null;
      final map = Map<String, dynamic>.from(e);
      final title = _str(map, ['message', 'description', 'status', 'event']) ?? 'Update';
      String location = '';
      final locRaw = map['location'] ?? map['city_locality'] ?? map['city'];
      if (locRaw is String) {
        location = locRaw;
      } else if (locRaw is Map) {
        location = [locRaw['city'], locRaw['state'], locRaw['country']]
            .whereType<String>().join(', ');
      }
      // ShipEngine flat location fields
      if (location.isEmpty) {
        location = [
          map['city_locality'], map['state_province'], map['country_code']
        ].whereType<String>().where((s) => s.isNotEmpty).join(', ');
      }
      final tsRaw = _str(map, ['timestamp', 'occurred_at', 'status_date', 'date']) ?? '';
      return TrackingEvent(
        title:     title,
        location:  location,
        timestamp: _formatDate(tsRaw),
      );
    }).whereType<TrackingEvent>().toList();
  }

  TrackingStatus _parseStatus(String? s) {
    switch ((s ?? '').toUpperCase()) {
      case 'DELIVERED':                    return TrackingStatus.delivered;
      case 'DE':                           return TrackingStatus.delivered;
      case 'TRANSIT':
      case 'IN_TRANSIT':
      case 'IT':                           return TrackingStatus.inTransit;
      case 'OUT_FOR_DELIVERY':
      case 'OD':                           return TrackingStatus.outForDelivery;
      case 'AT':                           return TrackingStatus.outForDelivery;
      case 'PRE_TRANSIT':
      case 'UN':
      case 'UNKNOWN':
      case 'LABEL_CREATED':
      case 'AC':                           return TrackingStatus.processing;
      case 'FAILURE':
      case 'RETURNED':
      case 'EX':
      case 'EXCEPTION':                    return TrackingStatus.exception;
      default:                             return TrackingStatus.inTransit;
    }
  }

  /// Detect which ShipEngine carrier key to use from the tracking number
  String _detectCarrierKey(String code) {
    // Royal Mail: starts RM/JD or matches international format
    if (RegExp(r'^[A-Z]{2}\d{9}[A-Z]{2}$').hasMatch(code)) return 'royal_mail';
    if (code.startsWith('RM') || code.startsWith('JD')) return 'royal_mail';
    // Evri
    if (code.startsWith('EV') || RegExp(r'^\d{16}$').hasMatch(code)) return 'evri';
    // DPD
    if (code.startsWith('DP') || RegExp(r'^\d{14}$').hasMatch(code)) return 'dpd';
    // FedEx
    if (RegExp(r'^\d{12}$').hasMatch(code) || RegExp(r'^\d{15}$').hasMatch(code)) return 'fedex';
    // InPost → GlobalPost as closest
    if (code.startsWith('IP')) return 'globalpost';
    // Yodel
    if (code.startsWith('YD')) return 'yodel';
    // Parcelforce
    if (code.startsWith('PF') || RegExp(r'^(GE|GK|GV|GW)\d{7}GB$').hasMatch(code)) return 'parcelforce';
    // DHL (uses FedEx UK carrier in ShipStation)
    if (code.startsWith('1Z') || code.startsWith('DH')) return 'fedex';
    return 'royal_mail';
  }

  String _friendlyCarrier(String key) {
    const map = {
      'royal_mail':  'Royal Mail',
      'evri':        'Evri',
      'dpd':         'DPD',
      'fedex':       'FedEx',
      'globalpost':  'GlobalPost',
      'yodel':       'Yodel',
      'parcelforce': 'Parcelforce',
    };
    return map[key] ?? key;
  }

  Color _courierColor(String key) {
    switch (key) {
      case 'royal_mail':  return const Color(0xFFE30613);
      case 'evri':        return const Color(0xFF8B5CF6);
      case 'dpd':         return const Color(0xFFE8001C);
      case 'fedex':       return const Color(0xFF4D148C);
      case 'globalpost':  return const Color(0xFF0284C7);
      case 'yodel':       return const Color(0xFF6D28D9);
      case 'parcelforce': return const Color(0xFF003087);
      default:            return const Color(0xFF6B6B6B);
    }
  }

  String _formatDate(String raw) {
    if (raw.isEmpty) return '';
    try {
      final dt = DateTime.parse(raw).toLocal();
      const months = ['Jan','Feb','Mar','Apr','May','Jun',
        'Jul','Aug','Sep','Oct','Nov','Dec'];
      return '${dt.day} ${months[dt.month - 1]} ${dt.year}, '
          '${dt.hour.toString().padLeft(2,'0')}:'
          '${dt.minute.toString().padLeft(2,'0')}';
    } catch (_) {
      return raw;
    }
  }

  void reset() {
    isLoading    = false;
    hasError     = false;
    errorMessage = '';
    result       = null;
    notifyListeners();
  }
}