// lib/data/country_data.dart

class CountryEntry {
  final String name;
  final String code;      // ISO-2  e.g. "US"
  final String dialCode;  // e.g.  "+1"
  final String flag;      // emoji flag
  final List<String> states; // empty = no state/province picker

  const CountryEntry({
    required this.name,
    required this.code,
    required this.dialCode,
    required this.flag,
    this.states = const [],
  });
}

const List<CountryEntry> kCountries = [
  CountryEntry(name: 'Afghanistan',       code: 'AF', dialCode: '+93',  flag: '🇦🇫'),
  CountryEntry(name: 'Albania',           code: 'AL', dialCode: '+355', flag: '🇦🇱'),
  CountryEntry(name: 'Algeria',           code: 'DZ', dialCode: '+213', flag: '🇩🇿'),
  CountryEntry(name: 'Argentina',         code: 'AR', dialCode: '+54',  flag: '🇦🇷',
      states: ['Buenos Aires','Córdoba','Santa Fe','Mendoza','Tucumán','Entre Ríos',
        'Salta','Misiones','Chaco','Corrientes','Santiago del Estero','San Juan',
        'Jujuy','Río Negro','Neuquén','Formosa','Chubut','San Luis','Catamarca',
        'La Rioja','La Pampa','Santa Cruz','Tierra del Fuego']),
  CountryEntry(name: 'Australia',         code: 'AU', dialCode: '+61',  flag: '🇦🇺',
      states: ['New South Wales','Victoria','Queensland','Western Australia',
        'South Australia','Tasmania','Australian Capital Territory','Northern Territory']),
  CountryEntry(name: 'Austria',           code: 'AT', dialCode: '+43',  flag: '🇦🇹'),
  CountryEntry(name: 'Bangladesh',        code: 'BD', dialCode: '+880', flag: '🇧🇩'),
  CountryEntry(name: 'Belgium',           code: 'BE', dialCode: '+32',  flag: '🇧🇪'),
  CountryEntry(name: 'Brazil',            code: 'BR', dialCode: '+55',  flag: '🇧🇷',
      states: ['Acre','Alagoas','Amapá','Amazonas','Bahia','Ceará','Espírito Santo',
        'Goiás','Maranhão','Mato Grosso','Mato Grosso do Sul','Minas Gerais','Pará',
        'Paraíba','Paraná','Pernambuco','Piauí','Rio de Janeiro','Rio Grande do Norte',
        'Rio Grande do Sul','Rondônia','Roraima','Santa Catarina','São Paulo',
        'Sergipe','Tocantins','Distrito Federal']),
  CountryEntry(name: 'Canada',            code: 'CA', dialCode: '+1',   flag: '🇨🇦',
      states: ['Alberta','British Columbia','Manitoba','New Brunswick',
        'Newfoundland and Labrador','Northwest Territories','Nova Scotia','Nunavut',
        'Ontario','Prince Edward Island','Quebec','Saskatchewan','Yukon']),
  CountryEntry(name: 'Chile',             code: 'CL', dialCode: '+56',  flag: '🇨🇱'),
  CountryEntry(name: 'China',             code: 'CN', dialCode: '+86',  flag: '🇨🇳',
      states: ['Beijing','Shanghai','Guangdong','Zhejiang','Jiangsu','Sichuan',
        'Hunan','Hubei','Shandong','Henan','Hebei','Liaoning','Heilongjiang',
        'Jilin','Shaanxi','Fujian','Anhui','Jiangxi','Guangxi','Yunnan','Guizhou',
        'Hainan','Qinghai','Gansu','Inner Mongolia','Ningxia','Xinjiang','Tibet',
        'Chongqing','Tianjin']),
  CountryEntry(name: 'Colombia',          code: 'CO', dialCode: '+57',  flag: '🇨🇴'),
  CountryEntry(name: 'Croatia',           code: 'HR', dialCode: '+385', flag: '🇭🇷'),
  CountryEntry(name: 'Cyprus',            code: 'CY', dialCode: '+357', flag: '🇨🇾'),
  CountryEntry(name: 'Czech Republic',    code: 'CZ', dialCode: '+420', flag: '🇨🇿'),
  CountryEntry(name: 'Denmark',           code: 'DK', dialCode: '+45',  flag: '🇩🇰'),
  CountryEntry(name: 'Egypt',             code: 'EG', dialCode: '+20',  flag: '🇪🇬'),
  CountryEntry(name: 'Finland',           code: 'FI', dialCode: '+358', flag: '🇫🇮'),
  CountryEntry(name: 'France',            code: 'FR', dialCode: '+33',  flag: '🇫🇷'),
  CountryEntry(name: 'Germany',           code: 'DE', dialCode: '+49',  flag: '🇩🇪'),
  CountryEntry(name: 'Ghana',             code: 'GH', dialCode: '+233', flag: '🇬🇭'),
  CountryEntry(name: 'Greece',            code: 'GR', dialCode: '+30',  flag: '🇬🇷'),
  CountryEntry(name: 'Hong Kong',         code: 'HK', dialCode: '+852', flag: '🇭🇰'),
  CountryEntry(name: 'Hungary',           code: 'HU', dialCode: '+36',  flag: '🇭🇺'),
  CountryEntry(name: 'India',             code: 'IN', dialCode: '+91',  flag: '🇮🇳',
      states: ['Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chhattisgarh',
        'Goa','Gujarat','Haryana','Himachal Pradesh','Jharkhand','Karnataka','Kerala',
        'Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland',
        'Odisha','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telangana','Tripura',
        'Uttar Pradesh','Uttarakhand','West Bengal','Delhi','Jammu & Kashmir','Ladakh']),
  CountryEntry(name: 'Indonesia',         code: 'ID', dialCode: '+62',  flag: '🇮🇩'),
  CountryEntry(name: 'Ireland',           code: 'IE', dialCode: '+353', flag: '🇮🇪'),
  CountryEntry(name: 'Israel',            code: 'IL', dialCode: '+972', flag: '🇮🇱'),
  CountryEntry(name: 'Italy',             code: 'IT', dialCode: '+39',  flag: '🇮🇹'),
  CountryEntry(name: 'Japan',             code: 'JP', dialCode: '+81',  flag: '🇯🇵',
      states: ['Hokkaido','Aomori','Iwate','Miyagi','Akita','Yamagata','Fukushima',
        'Ibaraki','Tochigi','Gunma','Saitama','Chiba','Tokyo','Kanagawa','Niigata',
        'Toyama','Ishikawa','Fukui','Yamanashi','Nagano','Shizuoka','Aichi','Mie',
        'Shiga','Kyoto','Osaka','Hyogo','Nara','Wakayama','Tottori','Shimane',
        'Okayama','Hiroshima','Yamaguchi','Tokushima','Kagawa','Ehime','Kochi',
        'Fukuoka','Saga','Nagasaki','Kumamoto','Oita','Miyazaki','Kagoshima','Okinawa']),
  CountryEntry(name: 'Jordan',            code: 'JO', dialCode: '+962', flag: '🇯🇴'),
  CountryEntry(name: 'Kenya',             code: 'KE', dialCode: '+254', flag: '🇰🇪'),
  CountryEntry(name: 'Kuwait',            code: 'KW', dialCode: '+965', flag: '🇰🇼'),
  CountryEntry(name: 'Malaysia',          code: 'MY', dialCode: '+60',  flag: '🇲🇾',
      states: ['Johor','Kedah','Kelantan','Malacca','Negeri Sembilan','Pahang',
        'Penang','Perak','Perlis','Sabah','Sarawak','Selangor','Terengganu',
        'Kuala Lumpur','Labuan','Putrajaya']),
  CountryEntry(name: 'Mexico',            code: 'MX', dialCode: '+52',  flag: '🇲🇽',
      states: ['Aguascalientes','Baja California','Baja California Sur','Campeche',
        'Chiapas','Chihuahua','Coahuila','Colima','Durango','Guanajuato','Guerrero',
        'Hidalgo','Jalisco','México','Michoacán','Morelos','Nayarit','Nuevo León',
        'Oaxaca','Puebla','Querétaro','Quintana Roo','San Luis Potosí','Sinaloa',
        'Sonora','Tabasco','Tamaulipas','Tlaxcala','Veracruz','Yucatán','Zacatecas',
        'Mexico City']),
  CountryEntry(name: 'Morocco',           code: 'MA', dialCode: '+212', flag: '🇲🇦'),
  CountryEntry(name: 'Netherlands',       code: 'NL', dialCode: '+31',  flag: '🇳🇱'),
  CountryEntry(name: 'New Zealand',       code: 'NZ', dialCode: '+64',  flag: '🇳🇿',
      states: ['Auckland','Wellington','Canterbury','Waikato','Bay of Plenty',
        'Otago','Hawke\'s Bay','Manawatu-Whanganui','Southland','Taranaki',
        'Northland','Marlborough','Gisborne','Nelson','Tasman','West Coast']),
  CountryEntry(name: 'Nigeria',           code: 'NG', dialCode: '+234', flag: '🇳🇬',
      states: ['Abia','Adamawa','Akwa Ibom','Anambra','Bauchi','Bayelsa','Benue',
        'Borno','Cross River','Delta','Ebonyi','Edo','Ekiti','Enugu','Gombe','Imo',
        'Jigawa','Kaduna','Kano','Katsina','Kebbi','Kogi','Kwara','Lagos','Nasarawa',
        'Niger','Ogun','Ondo','Osun','Oyo','Plateau','Rivers','Sokoto','Taraba',
        'Yobe','Zamfara','FCT']),
  CountryEntry(name: 'Norway',            code: 'NO', dialCode: '+47',  flag: '🇳🇴'),
  CountryEntry(name: 'Oman',              code: 'OM', dialCode: '+968', flag: '🇴🇲'),
  CountryEntry(name: 'Pakistan',          code: 'PK', dialCode: '+92',  flag: '🇵🇰',
      states: ['Punjab','Sindh','Khyber Pakhtunkhwa','Balochistan',
        'Gilgit-Baltistan','Azad Kashmir','Islamabad Capital Territory']),
  CountryEntry(name: 'Philippines',       code: 'PH', dialCode: '+63',  flag: '🇵🇭'),
  CountryEntry(name: 'Poland',            code: 'PL', dialCode: '+48',  flag: '🇵🇱'),
  CountryEntry(name: 'Portugal',          code: 'PT', dialCode: '+351', flag: '🇵🇹'),
  CountryEntry(name: 'Qatar',             code: 'QA', dialCode: '+974', flag: '🇶🇦'),
  CountryEntry(name: 'Romania',           code: 'RO', dialCode: '+40',  flag: '🇷🇴'),
  CountryEntry(name: 'Russia',            code: 'RU', dialCode: '+7',   flag: '🇷🇺'),
  CountryEntry(name: 'Saudi Arabia',      code: 'SA', dialCode: '+966', flag: '🇸🇦'),
  CountryEntry(name: 'Singapore',         code: 'SG', dialCode: '+65',  flag: '🇸🇬'),
  CountryEntry(name: 'South Africa',      code: 'ZA', dialCode: '+27',  flag: '🇿🇦',
      states: ['Eastern Cape','Free State','Gauteng','KwaZulu-Natal','Limpopo',
        'Mpumalanga','North West','Northern Cape','Western Cape']),
  CountryEntry(name: 'South Korea',       code: 'KR', dialCode: '+82',  flag: '🇰🇷'),
  CountryEntry(name: 'Spain',             code: 'ES', dialCode: '+34',  flag: '🇪🇸',
      states: ['Andalusia','Aragon','Asturias','Balearic Islands','Basque Country',
        'Canary Islands','Cantabria','Castilla-La Mancha','Castile and León',
        'Catalonia','Extremadura','Galicia','La Rioja','Madrid','Murcia',
        'Navarre','Valencia']),
  CountryEntry(name: 'Sri Lanka',         code: 'LK', dialCode: '+94',  flag: '🇱🇰'),
  CountryEntry(name: 'Sweden',            code: 'SE', dialCode: '+46',  flag: '🇸🇪'),
  CountryEntry(name: 'Switzerland',       code: 'CH', dialCode: '+41',  flag: '🇨🇭'),
  CountryEntry(name: 'Taiwan',            code: 'TW', dialCode: '+886', flag: '🇹🇼'),
  CountryEntry(name: 'Thailand',          code: 'TH', dialCode: '+66',  flag: '🇹🇭'),
  CountryEntry(name: 'Turkey',            code: 'TR', dialCode: '+90',  flag: '🇹🇷'),
  CountryEntry(name: 'Ukraine',           code: 'UA', dialCode: '+380', flag: '🇺🇦'),
  CountryEntry(name: 'United Arab Emirates', code: 'AE', dialCode: '+971', flag: '🇦🇪'),
  CountryEntry(name: 'United States',     code: 'US', dialCode: '+1',   flag: '🇺🇸',
      states: ['Alabama','Alaska','Arizona','Arkansas','California','Colorado',
        'Connecticut','Delaware','Florida','Georgia','Hawaii','Idaho','Illinois',
        'Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland',
        'Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana',
        'Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York',
        'North Carolina','North Dakota','Ohio','Oklahoma','Oregon','Pennsylvania',
        'Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah',
        'Vermont','Virginia','Washington','West Virginia','Wisconsin','Wyoming',
        'District of Columbia']),
  CountryEntry(name: 'Vietnam',           code: 'VN', dialCode: '+84',  flag: '🇻🇳'),
  CountryEntry(name: 'Zimbabwe',          code: 'ZW', dialCode: '+263', flag: '🇿🇼'),
];